version: '3'
services:
  app:
    image: node:latest
    container_name: foodcountry-vue
    ports:
      - 8090:8090
    volumes:
      - ./:/app
    restart: always
    working_dir: /app
    entrypoint: npm run serve
